Repository the-julge/the-julge, pull requests merged in 2024-03, with the labels that each got.

#9 ✨ TJ-2 로그인 페이지 레이아웃
  components/Input/index.tsx
  components/Input/types/type.ts
  components/Input/types/types.ts
  lib/constants/errorMessage.ts
  pages/signin/components/SigninForm/index.tsx
  pages/signin/components/ToSignup/index.tsx
  pages/signin/index.tsx
  pages/signin/types/types.ts
Labels: feature

#6 ♻️ TJ-6 파일, 폴더명, emotion 선언 위치 수정
  components/Gnb/components/HeaderButtons.tsx
  components/Gnb/components/NotiButton.tsx
  components/Gnb/components/SearchBar.tsx
  components/Gnb/components/UiButton.tsx
  components/Gnb/components/UiGnb.tsx
  components/Gnb/index.tsx
  components/Gnb/styles/fonstStyle.ts
Labels: refactor

#7 ✨ TJ-6 POST CARD 추가
  components/Post/components/Overlay.tsx
  components/Post/components/UiImage.tsx
  components/Post/components/UiPostContent.tsx
  components/Post/components/WageFlag.tsx
  components/Post/index.tsx
  components/Post/utils/getWageIncreaseText.ts
  pages/index.tsx
  styles/fontsStyle.ts
  styles/global.ts
Labels: feature

#12 ✨ TJ-43 공고 등록 컴포넌트
  components/Button/Button.tsx
  components/Filter/Filter.tsx
  components/PostForm/FormContainer.tsx
  components/PostForm/InputComponent.tsx
  components/PostForm/PostForm.tsx
  components/PostForm/types/types.ts
  components/Toast/Toast.tsx
  contexts/ToastContext.tsx
  pages/_app.tsx
  pages/index.tsx
  styles/global.ts
Labels: feature

#13 ✨ TJ-26 가게 상세 페이지 추가 Input 컴포넌트 추가
  lib/constants/.md
  pages/myShop/components/Footer/index.tsx
  pages/myShop/components/MyShopInfo/index.tsx
  pages/myShop/index.tsx
  pages/myShop/register/components/Input/components/InputContent.tsx
  pages/myShop/register/components/Input/index.tsx
  pages/myShop/register/components/Input/types/types.ts
  pages/myShop/register/index.tsx
  public/images/arrow-down.svg
  public/images/arrow-up.svg
  public/images/envelop-square.svg
  public/images/facebook-square.svg
  public/images/instagram-square.svg
Labels: feature

#15 ✨ TJ-18 공고 상세 페이지 추가 및 useQuery를 이용한 데이터 불러오기
  hooks/.md
  hooks/useNoticeData.ts
  lib/apis/fetchData.tsx
  lib/utils/formatTimeRange.ts
  pages/_app.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/ApplicantList.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/EmployeeTable.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostCard.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostDetail.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostInformation.tsx
  pages/shops/[shopId]/notices/[noticeId]/index.tsx
  styles/fontsStyle.ts
Labels: feature

#16 ✨ TJ-48 맞춤 공고 기능 추가 axios, useQuery를 이용
  components/Post/index.tsx
  pages/home/components/PostList.ts/index.tsx
  pages/home/components/RecommendNotice/index.tsx
  pages/home/hooks/useUserQuery.ts
  pages/home/hooks/userRequest.ts
  pages/index.tsx
  types/PostType.ts
Labels: feature

#19 ✨ TJ-45 공고 등록 기능 구현
  components/Button/Button.tsx
  components/Filter/LocationBadgeBox.tsx
  components/PostForm/InputComponent.tsx
  components/PostForm/PostForm.tsx
  components/PostForm/Tooltip.tsx
  components/PostForm/index.tsx
  components/PostForm/types/types.ts
  contexts/ToastContext.tsx
  lib/apis/.md
  lib/apis/fetchData.tsx
  pages/shops/[shopId]/index.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/ApplicantList.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostDetail.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostInformation.tsx
  pages/shops/[shopId]/notices/[noticeId]/index.tsx
  pages/shops/[shopId]/types/types.ts
  pages/shops/[shopId]/utils/formatDateString.ts
  public/images/tooltip-icon.svg
  types/apiTypes.ts
Labels: feature

#21 ✨ TJ-46 회원가입 페이지 기능 구현
  lib/constants/errorMessage.ts
  lib/utils/validateFormData.ts
  pages/signup/components/SignupForm/TypeButton.tsx
  pages/signup/components/SignupForm/UserTypeSelect.tsx
  pages/signup/components/SignupForm/index.tsx
  pages/signup/components/UserTypeSelect/index.tsx
  pages/signup/index.tsx
  pages/signup/types/types.ts
Labels: feature

#22 ✨TJ-63 search 기능 구현
  components/Gnb/hook/useRequests.ts
  components/Post/components/WageFlag.tsx
  components/Post/utils/getWageIncreaseText.ts
  hooks/useUserQuery.ts
  hooks/userRequest.ts
  pages/index.tsx
  pages/search/components/AllNotice/index.tsx
  pages/search/components/AllNoticeHeader/index.tsx
  pages/search/components/HeaderButtons/index.tsx
  pages/search/components/HeaderText/index.tsx
  pages/search/components/Pagination/index.tsx
  pages/search/components/PostList/index.tsx
  pages/search/components/RecommendNotice/index.tsx
  pages/search/index.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostInformation.tsx
  tsconfig.json
Labels: feature

#23 ✨ TJ-7 페이지네이션 구현
  components/Pagination/components/ArrowButton.tsx
  components/Pagination/components/PageButton.tsx
  components/Pagination/index.tsx
  lib/utils/getPaginationArray.ts
Labels: feature

#25 🐛 TJ-69 페이지네이션 쿼리스트링 여러개 적용
  components/Pagination/index.tsx
  lib/utils/objectToQueryString.ts
Labels: fix

#26 ✨ TJ-67 index, search 페이지 페이지네이션 연동
  components/Pagination/index.tsx
  pages/index.page.tsx
  pages/search/components/AllNotice/index.tsx
  pages/search/components/Pagination/index.tsx
  pages/search/index.page.tsx
Labels: feature

#27 ✨ TJ-24 프로필 페이지 신청 내역 레이아웃
  components/Table/components/Header/index.tsx
  components/Table/components/TableBody/OwnerTableRow.tsx
  components/Table/components/TableBody/PartTimerTableRow.tsx
  components/Table/components/TableBody/index.tsx
  components/Table/index.tsx
  pages/my-profile/ApplyHistory/index.tsx
  pages/my-profile/Profile/index.tsx
  pages/my-profile/index.page.tsx
Labels: feature

#31 ✨ TJ-62 쿠키에 토큰 및 유저 정보 담기
  pages/signin/components/SigninForm/index.tsx
Labels: feature

#32 ✨ TJ-74 쿠키 유틸 함수 추가
  lib/utils/getCookies.ts
  pages/api/auth.page.ts
  pages/signin/components/SigninForm/index.tsx
  pages/signup/components/SignupForm/index.tsx
Labels: feature

#33 ♻️ TJ-75 비동기 유틸 함수를 커스텀 훅으로 변경
  hooks/useCookies.ts
  lib/utils/getCookies.ts
Labels: refactor

#38 ✨ TJ-62 신청 내역 API 연동
  pages/my-profile/Profile/index.tsx
  pages/my-profile/components/ApplyHistory/index.tsx
  pages/my-profile/components/UserProfile/index.tsx
  pages/my-profile/hooks/useApplicationHistory.ts
  pages/my-profile/hooks/useProfileData.ts
  pages/my-profile/index.page.tsx
Labels: feature

#39 ✨ TJ-56 공고 상세 사장님 지원목록 렌더링 및 승인/거절 요청
  components/Button/Button.tsx
  components/Table/components/TableBody/OwnerTableRow.tsx
  components/Table/components/TableBody/index.tsx
  components/Table/index.tsx
  lib/apis/fetchData.tsx
  lib/apis/handleAxiosError.ts
  lib/types/Application.ts
  pages/shops/[shopId]/index.page.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employee/EmployeeButton.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employee/index.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employer/ApplicantList.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employer/EmployerButton.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employer/index.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/ModalContent.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostCard.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostDetail.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostInformation.tsx
  pages/shops/[shopId]/notices/[noticeId]/index.page.tsx
  pages/shops/[shopId]/notices/[noticeId]/utils/transformItems.ts
Labels: feature

#40 ✨ TJ-66 내 프로필 레이아웃 및 연동
  pages/my-profile/components/ProfileCard.tsx/ProfileContent.tsx
  pages/my-profile/components/ProfileCard.tsx/index.tsx
  pages/my-profile/components/UserProfile/index.tsx
  public/images/phone.svg
Labels: feature

#42 ✨ TJ-73 프로필 프로필 등록/수정 페이지 레이아웃
  components/Input/index.tsx
  components/Input/types/types.ts
  pages/my-profile/components/ProfileCard.tsx/index.tsx
  pages/my-profile/components/UserProfile/index.tsx
  pages/my-profile/edit/ProfileEditForm/EditFormInput.tsx
  pages/my-profile/edit/ProfileEditForm/index.tsx
  pages/my-profile/edit/index.page.tsx
Labels: feature

#35 ✨ TJ-64 GNB 기능
  components/Gnb/components/HeaderButtons.tsx
  components/Gnb/components/NotiButton.tsx
  components/Gnb/components/UiGnb.tsx
  components/Gnb/hook/useLogout.ts
  components/Gnb/hook/useRequests.ts
  components/Gnb/hook/useUserQuery.ts
  components/Gnb/index.tsx
  components/Layout/index.tsx
  components/NotificationModal/components/Notification.tsx
  components/NotificationModal/hooks/useUserQuery.ts
  components/NotificationModal/hooks/userRequest.ts
  components/NotificationModal/index.tsx
  components/NotificationModal/types/types.ts
  components/NotificationModal/utils/extractNotificationInfo.ts
  pages/my-shop/index.page.tsx
  pages/my-shop/register/index.page.tsx
Labels: feature

#43 ♻️ TJ-80 홈페이지, search 페이지 리팩토링, 버그 수정
  components/DropDown/index.tsx
  components/Footer/index.tsx
  components/Gnb/components/UiGnb.tsx
  components/NoPost/index.tsx
  components/Post/components/Overlay.tsx
  components/Post/components/UiImage.tsx
  components/Post/components/UiPostContent.tsx
  components/Post/index.tsx
  pages/search/components/AllNotice/index.tsx
  pages/search/components/AllNoticeHeader/index.tsx
  pages/search/components/HeaderButtons/index.tsx
  pages/search/components/HeaderText/index.tsx
  pages/search/components/Pagination/index.tsx
  pages/search/components/PostList/index.tsx
  pages/search/components/PostList/util/renderPosts.tsx
  pages/search/components/RecommendNotice/index.tsx
  pages/search/constants/category.ts
  pages/search/hooks/useUserQuery.ts
  pages/search/hooks/userRequest.ts
  pages/search/utils/convertDate.ts
  pages/shops/[shopId]/notices/[noticeId]/components/Employee/RecentNotice.tsx
  styles/fontsStyle.ts
Labels: fix

#44 ✨ TJ-51 공고 등록 및 공고 상세 페이지 반응형 적용
  components/NotificationModal/index.tsx
  components/PostForm/index.tsx
  lib/constants/toastMessage.ts
  pages/shops/[shopId]/index.page.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employee/EmployeeButton.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employee/RecentNoticeContainer.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employer/ApplicantList.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/Employer/index.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostCard.tsx
  pages/shops/[shopId]/notices/[noticeId]/components/PostDetail.tsx
  pages/shops/[shopId]/notices/[noticeId]/edit/index.page.tsx
  pages/shops/[shopId]/notices/[noticeId]/index.page.tsx
  pages/shops/[shopId]/utils/validateFormData.ts
Labels: design

#48 ✨ TJ-76 프로필 등록 페이지 기능 구현
  lib/constants/errorMessage.ts
  pages/my-profile/edit/ProfileEditForm/EditFormInput.tsx
  pages/my-profile/edit/ProfileEditForm/index.tsx
  pages/my-profile/edit/components/ProfileEditForm/EditFormInput.tsx
  pages/my-profile/edit/components/ProfileEditForm/FormContent.tsx
  pages/my-profile/edit/components/ProfileEditForm/TextArea.tsx
  pages/my-profile/edit/components/ProfileEditForm/Title.tsx
  pages/my-profile/edit/components/ProfileEditForm/index.tsx
  pages/my-profile/edit/index.page.tsx
  pages/my-profile/edit/utils/validateFormData.ts
Labels: feature

#55 💄 TJ-77 테이블 상태칸 css 적용
  components/Table/components/TableBody/PartTimerTableRow.tsx
Labels: feature

#65 💄 TJ-95 페이지네이션 화살표 이미지 정상화
  components/Pagination/components/ArrowButton.tsx
  public/images/arrow-left-black.svg
  public/images/arrow-right-gray.svg
Labels: design

#71 TJ-102 추천공고, 전체공고 반응형 수정, 전체 공고 스켈레톤 ui 추가
  components/Filter/Filter.tsx
  pages/search/components/AllNotice/index.tsx
  pages/search/components/RecommendNotice/index.tsx
  pages/search/hooks/useRequestApi.ts
  pages/search/utils/convertDate.ts
Labels: bug, design

#72 ✨ TJ-103 토스트 적용 및 useQuery 적용
  hooks/useCookies.ts
  pages/my-profile/edit/components/ProfileEditForm/index.tsx
  pages/my-profile/hooks/useProfileData.ts
  pages/signin/components/SigninForm/index.tsx
  pages/signup/components/SignupForm/index.tsx
Labels: feature
